### ISSUE TITLE
DVCC not working

### ISSUE THREAD

**Issue by red0909** [stuartpittaway/diyBMSv4ESP32#173]
thats why my sma inverter crashes when i switch to victron canbus instead pylontech

the bms does not transmit cvl and ccl in victron mode

![dvcc victron](https://user-images.githubusercontent.com/93882193/219733593-976c1bd6-c824-4214-8a19-3047a55e9dfa.jpg)

next problem
cvl ccl and dcl are correct at pylontech setting but the dvcc doesnt work too...

tried reboot of bms and venus os after settings change and tried to delete the bms from venus os but it still dont work

controller fw 2023 02 14

**Comment by laserranger3000** [comment]
I have the same problem.
It works when I set the check box for "prevent charging", then the values are sent correctly to the gx device.
It seems that the setting is inverted.
-> I'm using 2023-02-16
-> I imported my old settings (maybe that has an influence?)

**Comment by HerrFrodo1** [comment]
Yes, the Setting is inverted. I use 2023-02-16 too, without imported settings. 
If Prevent charge is aktivated, the cerbo gets the right values.

**Comment by red0909** [comment]
ok i have activated "prevent charging" now the values are there but my charge controller (450/100) still wont charge in dvcc mode

not in pylontech and not in victron mode
i know it charge because the old style canbus in the old firmaware was working with dvcc charging

**Comment by stuartpittaway** [comment]
This should be fixed now - you will need to switch "prevent charging" off.

**Comment by red0909** [comment]
now with [Release-2023-02-20] at victron canbus the dvcc work

but at the pylontech canbus, dvcc still doesnt work
if battery id B009 is used then venus os will force dvcc on(it can be manualy edited in some venus os fils not to force it on)

**Comment by stuartpittaway** [comment]
> but at the pylontech canbus, dvcc still doesnt work

I've never used PylonTech battery on Victron kit - I would normally advise not to and use the genuine Victron protocols instead.

Are you using the DIYBMS current monitor?  If not, perhaps it requires those missing messages (current, state of charge etc.)

**Comment by red0909** [comment]
i have the shunt installed and running with latest firmware

but pylontech on victron should support dvcc, it is supported by victron.
maybe you can fix this in future, for me now the victron canbus does the job.
